### PR TITLE
Pre-processing step is nearly complete!

### LINKED ISSUE #8: `constants.py` in Housekeeping Instructions
Will `constants.py` be used primarily for denoting where the dataset locations are and information about it?

If so, then we should probably hide it, as it is likely we have each put the dataset locations in different folders. It should not be pushed to Github.

If not, then we should probably create two files: one private and one public.

### PR DESCRIPTION
**Pull request by jonah-chen**
Modified the preprocessing code works on my end. It is currently able to preprocess in parallel resulting in around a 5-10x performance gain. Key changes are 
- Allowing the code to work in parallel. `save_spectrogram`, `save_midi`, `midi_to_audio`, `save_spectrogram`, and `save_notes` are all capable to be parallelized. Good job!
- Introduced the ability to preprocess the entire dataset with one execution of `preprocess_batch.py`, while still keeping the functionality to preprocess a subset (1 year).
- Adopted the use of `.env` file for the user to store the global path to the datasets, processed data, and other files that is not stored in the project directory, which resolves #8.

### CODE REVIEW

**Comment by jonah-chen** [comment]
Do not merge until #17 is closed.

**Review by QiLinXue — COMMENTED** [review]
It may make sense to call `prepare_dirs()` in `preprocess_file()` as well.

**Comment by jonah-chen** [comment]
> It may make sense to call `prepare_dirs()` in `preprocess_file()` as well.

Unfortunately, this does not work because creating directories in parallel can cause issues. This was the reason I created `prepare_dirs` in the first place. Note https://github.com/jonah-chen/midi-shark/blob/7463f655c8bf010a6e906807f2cfb06f2449fc9e/processing/preprocess_batch.py#L63-L72 are not in `preprocess_file`, as they are the problematic lines.

**Comment by QiLinXue** [comment]
LGTM!

**Pull request merged**
