### PR TITLE
output to .npy instead of csv

### LINKED ISSUE #15: Inefficient use of disk space for `notes_generated`
I have noticed that the `notes_generated` folder contains `.csv` files of note information (the code that generated these files is in `preprocessing/process_midi::save_midi`). Is this intend to be directly read by a human? Please clarify why if it is. If it is not, it would be more efficient to store these in a binary format like `.npy`.

After this is fixed or clarified, I think I can execute the code to preprocess the full dataset, which should take between 2 and 4 hours.

### PR DESCRIPTION
**Pull request by joehattori**
Resolves https://github.com/jonah-chen/midi-shark/issues/15

### CODE REVIEW

**Comment by jonah-chen** [comment]
I think the changes may fix the issue for executing `process_midi.py`. However, the main issue on my end is with calling this function https://github.com/jonah-chen/midi-shark/blob/c2435e8b415e5dd4d1b1db8946aa59944b24c927/processing/process_midi.py#L52 when trying to preprocess the entire dataset. I think @QiLinXue wrote this function.

Also, I think you should merge to preproces/rough instead of to main, otherwise preproces/rough which we are currently working on will overwrite the changes.

**Review by jonah-chen — CHANGES_REQUESTED** [review]
I think the changes may fix the issue for executing `process_midi.py`. However, the main issue on my end is with calling this function https://github.com/jonah-chen/midi-shark/blob/c2435e8b415e5dd4d1b1db8946aa59944b24c927/processing/process_midi.py#L52 when trying to preprocess the entire dataset, which was not resolved. I think @QiLinXue wrote this function.

Also, I think you should merge to preproces/rough instead of to main, otherwise preproces/rough which we are currently working on will overwrite the changes.

**Comment by jonah-chen** [comment]
@joehattori I have integrated your changes to the preproces/rough branch with #17. If the changes look good to you, please merge #17 and close this without merging.

**Comment by QiLinXue** [comment]
Looks good to me. Merged #17 and will be closing this.

**Review by QiLinXue — COMMENTED** [review]
See comments.

**Pull request closed without merging**
